services:
  aqi-be:
    build:
      context: ./../be
      dockerfile: ./../be/aqi_be.dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH="/app/config.json"  # Container environment variable pointing to the config file
    volumes:
      - "D:/Mine/AirIndexProject/config.json:/app/config.json"  # Mount config.json from local to container
    depends_on:
      - postgres  # Ensure the Postgres container starts before the app

  postgres:
    image: postgres:16.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # These can be set in .env or passed as env variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists the database data

volumes:
  postgres_data:
    driver: local
